version: '3'

services:
  backend:
    image: java-api
    ports:
      - 9999:9999
    networks:
      - app-network

  frontend:
    image: frontend
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
